### ISSUE TITLE
Blank actions

### ISSUE THREAD

**Issue by dummied** [bendoane/SwingOut#45]
https://github.com/bendoane/SwingOut/blob/master/app/controllers/events_controller.rb#L47

Implement or remove.

**Comment by dummied** [comment]
More: https://github.com/bendoane/SwingOut/blob/master/app/controllers/users_controller.rb#L13

**Comment by bendoane** [comment]
The first one is already implemented...?

**Comment by dummied** [comment]
Line number moved around. I was referring to update and about

**Comment by bendoane** [comment]
fixed
