### ISSUE TITLE
Is this controller used anywhere?

### ISSUE THREAD

**Issue by dummied** [bendoane/SwingOut#48]
https://github.com/bendoane/SwingOut/blob/master/app/controllers/locations_controller.rb

If not, remove it (don't forget the routes)

**Comment by bendoane** [comment]
This is used for finding the locations nearest to the event on events#show

**Comment by dummied** [comment]
That wouldn't use the controller, though. Unless you have an API there that you're using.

**Comment by bendoane** [comment]
gotcha. Done!
