### ISSUE TITLE
Multiple id's on page

### ISSUE THREAD

**Issue by dummied** [bendoane/SwingOut#53]
https://github.com/bendoane/SwingOut/blob/master/app/views/events/index.html.erb#L6

**Comment by dummied** [comment]
https://github.com/bendoane/SwingOut/blob/master/app/views/info/my_events.html.erb#L13

**Comment by dummied** [comment]
https://github.com/bendoane/SwingOut/blob/master/app/views/info/my_events.html.erb#L16

**Comment by dummied** [comment]
https://github.com/bendoane/SwingOut/blob/master/app/views/info/my_events.html.erb#L35

**Comment by bendoane** [comment]
Has this been fixed by the partial?

**Comment by bendoane** [comment]
Add fixed via the partial
